module SkelHiyapal where

-- Haskell module generated by the BNF converter

import AbsHiyapal
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transId :: Id -> Result
transId x = case x of
  Id string -> failure x
transExp :: Exp -> Result
transExp x = case x of
  SinExpr intexp -> failure x
  Expr intexp exp -> failure x
transIntExp :: IntExp -> Result
transIntExp x = case x of
  Div intexp1 intexp2 -> failure x
  Sub intexp1 intexp2 -> failure x
  Add intexp1 intexp2 -> failure x
  Mul intexp1 intexp2 -> failure x
  Neg intexp -> failure x
  Nmb integer -> failure x
  Var id -> failure x

